language: android
jdk: oraclejdk8

# sudo false tells Travis to place the project into a docker environment
sudo: false

env:
  global:
  # The SDK version used to compile the project
  - ANDROID_API_LEVEL=26

  # The SDK version used for emulator tests
  - ANDROID_EMULATOR_LEVEL=18

  # The BuildTools version used by the project
  - ANDROID_BUILD_TOOLS_VERSION=27.0.3

  # Timeout timer
  - ADB_INSTALL_TIMEOUT=5 # minutes

android:
  components:
  # Used to run the latest revision of Android SDK Tools
  - tools
  - platform-tools

  # Used to assign BuildTools and API levels
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL
  - android-$ANDROID_EMULATOR_LEVEL

  # Used to retrieve the system image to run emulators during tests
  - sys-img-x86-android-$ANDROID_API_LEVEL
  - sys-img-armeabi-v7a-android-$ANDROID_EMULATOR_LEVEL

licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+

before_install:
- yes | sdkmanager "platforms;android-26"

# Used to provide permission for gradlew
- chmod +x gradlew

before_script:
# Create a virtual environment image called 'test' with specified Android API level
- echo no | android create avd --force -n test -t android-"$ANDROID_EMULATOR_LEVEL" --abi armeabi-v7a

# Start the emulator 'test' with no visuals and no audio
- emulator -avd test -no-window &

# Wait for the emulator to start
- android-wait-for-emulator

# Unlock device to run tests on an unlocked device
- adb shell input keyevent 82 &

script:
# './gradlew connectedCheck' executes tests located in src/androidTests/
- ./gradlew clean build connectedCheck -PdisablePreDex --stacktrace

