version: 2

jobs:
  build:
    docker:
      - image: circleci/android:api-26-alpha

    working_directory: ~/AntennaPod390

    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx1536m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError"'
      _JAVA_OPTIONS: "-Xms256m -Xmx1280m"

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-android-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-android-

      - run:
          Name: Release Build Test
          # To build release, we need to create a temporary keystore that can be used to sign the app
          command: |
            keytool -noprompt -genkey -v -keystore "app/keystore" -alias alias -storepass password -keypass password -keyalg RSA -validity 10 -dname "CN=antennapod.org, OU=dummy, O=dummy, L=dummy, S=dummy, C=US"
            ./gradlew assemblePlayRelease :core:testPlayReleaseUnitTest -PdisablePreDex
          no_output_timeout: 1800

      - run:
          Name: Unit Tests in Free Debug Build
          command: |
            ./gradlew testFreeDebugUnitTest

      - run:
          Name: UI Tests in Firebase
          command: |
            if [ $CIRCLE_BRANCH == "master" ] || [ $CIRCLE_BRANCH == "firebase" ]; then
              ./gradlew clean
              ./gradlew :app:assembleFreeDebug
              ./gradlew :app:assembleFreeDebugAndroidTest
              echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
              sudo gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
              sudo gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
              sudo gcloud firebase test android run \
              --test-targets "class de.test.antennapod.ui.MainActivityTest" \
              --type instrumentation \
              --app /home/circleci/AntennaPod390/app/build/outputs/apk/free/debug/app-free-debug.apk \
              --test /home/circleci/AntennaPod390/app/build/outputs/apk/androidTest/free/debug/app-free-debug-androidTest.apk
            fi

      - store_artifacts:
          path: app/build/outputs/apk
          destination: apks

      - save_cache:
          paths:
            - ~/.android
            - ~/.gradle
            - ~/android
          key: v1-android-{{ checksum "build.gradle" }}